import './globals.css';

import type { Metadata } from 'next';
import { Atkinson_Hyperlegible_Mono, Atkinson_Hyperlegible_Next } from 'next/font/google';

const atkinsonHyperlegible = Atkinson_Hyperlegible_Next({
  variable: '--font-atkinson-hyperlegible',
  subsets: ['latin'],
  fallback: ['sans-serif', 'system-ui'],
});

const atkinsonHyperlegibleMono = Atkinson_Hyperlegible_Mono({
  variable: '--font-atkinson-hyperlegible-mono',
  subsets: ['latin'],
  fallback: ['monospace', 'ui-monospace'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${atkinsonHyperlegible.variable} ${atkinsonHyperlegibleMono.variable} antialiased`}>
        <nav
          className={`fixed top-0 left-0 z-50 flex h-18 w-full items-center justify-between bg-gray-100 px-6 shadow`}
        >
          <div className={`flex-1 text-left text-4xl font-bold tracking-wide text-lime-400`}>
            <span className="whitespace-nowrap">suspiciously specific stickers</span>
          </div>
          <div className={`flex flex-2 justify-center gap-8 text-base font-medium`}>
            <a href="/gallery" className="text-lime-400 hover:underline">
              gallery
            </a>
            <a href="/about" className="text-lime-400 hover:underline">
              about
            </a>
            <a href="/contact" className="text-lime-400 hover:underline">
              contact
            </a>
          </div>
          <div className="flex-1"></div>
        </nav>
        {children}
      </body>
    </html>
  );
}
